### ISSUE TITLE
编译安卓11twrp提示空间不足

### ISSUE THREAD

**Issue by ZhcnPanda** [azwhikaru/Action-Recovery-builder#10]
如图
![QQ图片20220107142702](https://user-images.githubusercontent.com/57992344/148501720-65a3536b-c6e8-4b0c-895f-56bd3a15b93e.png)
![QQ图片20220107142820](https://user-images.githubusercontent.com/57992344/148501857-3b85b4b8-4147-406d-9a54-458d28c67b4f.png)

**Comment by azwhikaru** [comment]
用的什么源码

**Comment by azwhikaru** [comment]
好的已经确认跑不动AOSP的11了，action可能到头了（悲
