### ISSUE TITLE
编译产物无法使用

### ISSUE THREAD

**Issue by ABCCCC55645687** [azwhikaru/Action-Recovery-builder#12]
你好！我用twrpdtgen生成了一份DeviceTree，并Fork了您的源码来**编译一份TWRP**，__过程0错误_，编译结果也正常_，也有编译产物（recovery.img），但是用dd刷入recovery分区并引导后，**手机在显示第一屏后黑屏，连接电脑后设备管理器中在通用串行设备总线下有我的手机（MI CC 9e），但手机黑屏，无任何反应**，请解决此问题！谢谢！
手机型号：小米CC9e
MIUI版本：12.5
Android版本：10
TWRP分支版本：twrp-9.0
Log文件+TWRP编译产物：
[logs_1.zip](https://github.com/azwhikaru/Action-Recovery-builder/files/7919793/logs_1.zip)

**Comment by azwhikaru** [comment]
我没有办法来适配任何一部具体的设备，我只能保证这个 Action 是严格按照典型的编译方式进行制作而不加带任何私活
如果编译后的镜像不能正常使用，请**检查你的 Device Tree**

**Comment by ABCCCC55645687** [comment]
行吧，看起来我得手搓一个设备树了哈哈哈。
