### ISSUE TITLE
lnitialize repo is wrong

### ISSUE THREAD

**Issue by chyinan** [azwhikaru/Action-Recovery-builder#20]
Run PATH=~/bin:$PATH
fatal: cannot obtain manifest git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
manifests:
fatal: unable to connect to github.com:
github.com[O: 140.82.113.4]: errno=Connection timed out
manifests: sleeping 4.0 seconds before retrying
manifests:
fatal: unable to connect to github.com:
github.com[O: 140.82.113.4]: errno=Connection timed out
Error: Process completed with exit code 1.

I don't know what's going on so I tried several times with different configs, but each time the same error code, so I came for help.
The device I am using is based on Android 8.1, so the version I use is the 2021/11/29 version, I used to compile it successfully once before, but it doesn't work now,
The new version seems to be only available for Android 9.0+ devices, so I don't know what to do.

**Comment by azwhikaru** [comment]
Please don't use 
'git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git', 

but 
'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git'.
