### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by MrMails** [azwhikaru/Action-Recovery-builder#24]
![Screenshot_20220907-222328_Chrome](https://user-images.githubusercontent.com/103464130/188960622-44f02c06-c402-4523-a2de-e43181141ff0.jpg)
I don't understand what I should put in the "MAKEFILE_NAME" line.  please help me to fix the error

**Comment by azwhikaru** [comment]
for your device, is 'omni_ASUS_AI2201.mk'
