### ISSUE TITLE
Build for ROG Phone 6 (AI2201)

### ISSUE THREAD

**Issue by jeanrivera** [azwhikaru/Action-Recovery-builder#26]
I am having this problem on building

this is my device tree

https://github.com/jeanrivera/android_device_asus_ASUS_AI2201

23s
1s
Run source build/envsetup.sh
including device/asus/AI220[1](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:1)/vendorsetup.sh
/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/device/asus/AI2201/vendorsetup.sh:8: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/device/asus/AI2201/vendorsetup.sh:[9](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:10): add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/device/asus/AI2201/vendorsetup.sh:[10](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:11): add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:3[12](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:13):
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "omni_ASUS_AI2201.mk".
07:58:17 dumpvars failed with: exit status 1
Device ASUS_AI2201.mk not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for ASUS_AI2201.mk not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
In file included from build/make/core/config.mk:3[13](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:14):
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "omni_ASUS_AI2201.mk".
07:58:18 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:[16](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:17)0: error: Can not locate config makefile for product "omni_ASUS_AI2201.mk".
07:58:[18](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:19) dumpvars failed with: exit status 1

** Don't have a product spec for: 'omni_ASUS_AI2[20](https://github.com/jeanrivera/Action-Recovery-builder/actions/runs/3254891860/jobs/5343639928#step:18:21)1.mk'
** Do you have the right repo manifest?

Error: Process completed with exit code 1.

![Screenshot 2022-10-15 040239](https://user-images.githubusercontent.com/24832354/195976297-3510a007-219c-4106-bcf4-7c5bef7a1aac.jpg)

**Comment by azwhikaru** [comment]
Double check the parameters filled in when running the action, such as the name of the device or the path to a file?

**Comment by juic3b0x** [comment]
I don't know if you already fixed your issue but this means you need to edit your **AndroidProducts.mk** file and change this:
```
PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/omni_ASUS_AI2201.mk

COMMON_LUNCH_CHOICES := \
    omni_ASUS_AI2201-user \
    omni_ASUS_AI2201-userdebug \
    omni_ASUS_AI2201-eng
```

to

```
PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/twrp_ASUS_AI2201.mk

COMMON_LUNCH_CHOICES := \
    twrp_ASUS_AI2201-eng
```


Now, after looking at your device tree, you need to actually go edit every file you have and change **omni** to **twrp** in every instance. Then you wont see that error any longer.
