### ISSUE TITLE
Clone device tree error

### ISSUE THREAD

**Issue by whaletb** [azwhikaru/Action-Recovery-builder#36]
Hi,  I'm trying to build shrp using the action recovery builder but the build fails each time I tried and returns the following error.

<pre>Run git clone https://github.com/whaletb/device-tree-tecnokc8 -b v3_11.0 ./device/tecno/TECNO-KC8
  git clone https://github.com/whaletb/device-tree-tecnokc8 -b v3_11.0 ./device/tecno/TECNO-KC8
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.352-8/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.352-8/x64
Cloning into './device/tecno/TECNO-KC8'...
<b>fatal: Remote branch v3_11.0 not found in upstream origin</b>
Error: Process completed with exit code 128.</pre>

I'm not sure where the problem at. Please point me in the right direction.

**Comment by azwhikaru** [comment]
Apparently, your device tree repository does not contain a branch called 'v3_11.0', you should use 'main'
![image](https://user-images.githubusercontent.com/37921907/209540478-d8b70601-80b0-455e-8fec-77379af5769b.png)

**Comment by whaletb** [comment]
> Apparently, your device tree repository does not contain a branch called 'v3_11.0', you should use 'main' ![image](https://user-images.githubusercontent.com/37921907/209540478-d8b70601-80b0-455e-8fec-77379af5769b.png)

Thanks for the response. I didn't really understand the error at first but I figured it out. I just started using Github.

**Comment by whaletb** [comment]
I passed the cloning stage. Now the build is failing and I can't seem to understand the error log.

`Run source build/envsetup.sh
  source build/envsetup.sh
  repopick 5405 5540
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.352-8/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.352-8/x64
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/tecno/TECNO-KC8/AndroidProducts.mk:11: error: device/tecno/TECNO-KC8: omni_TECNO-KC8-user: Invalid variant: KC8.
21:28:22 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/tecno/TECNO-KC8/AndroidProducts.mk:11: error: device/tecno/TECNO-KC8: omni_TECNO-KC8-user: Invalid variant: KC8.
21:28:23 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/tecno/TECNO-KC8/AndroidProducts.mk:11: error: device/tecno/TECNO-KC8: omni_TECNO-KC8-user: Invalid variant: KC8.
21:28:23 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/tecno/TECNO-KC8/AndroidProducts.mk:11: error: device/tecno/TECNO-KC8: omni_TECNO-KC8-user: Invalid variant: KC8.
21:28:24 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/tecno/TECNO-KC8/AndroidProducts.mk:11: error: device/tecno/TECNO-KC8: omni_TECNO-KC8-user: Invalid variant: KC8.
21:28:25 dumpvars failed with: exit status 1
Can't find toolchain for unknown architecture: 
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/tecno/TECNO-KC8/AndroidProducts.mk:11: error: device/tecno/TECNO-KC8: omni_TECNO-KC8-user: Invalid variant: KC8.
21:28:26 dumpvars failed with: exit status 1
Error: Process completed with exit code 1.`

**Comment by azwhikaru** [comment]
This error usually occurs because you have only changed something in a file in the device tree, but it has not been modified in all files that reference it. 

You need to double check your device tree for some naming conflicts: I noticed that something about TECNO-KC8 and KC8 was changed in your commit.

**Comment by azwhikaru** [comment]
Too long no reply, close.
